### PR TITLE
Remove whitespace from string before parsing to enum

### PR DESCRIPTION
**Pull request by OskarKlintrot**
This is related to #101, my main reason I created #101 is to be able to use a normal string (ie `United States` instead of `UnitedStates`) in drop-downs but still be able to get them as enums in .NET. Could this be something interesting? I still can't run the project on my computer though.

### CODE REVIEW

**Comment by OskarKlintrot** [comment]
Now I have tested the code in my current project, it works 👍

**Comment by quirijnslings** [comment]
@OskarKlintrot There is a merge conflict on this one. Can you please resolve this by merging the latest develop branch into your branche, fix the conflicts, and commit your branch again?

**Comment by OskarKlintrot** [comment]
I resolved it in GitHub's online merge tool (didn't even know they had one until now!) since I don't have the project on my machine anymore.

**Comment by ThijsBorst** [comment]
Thanks!

**Comment by OskarKlintrot** [comment]
Thank you!

**Pull request merged**
